# Generated by Django 2.0.3 on 2018-12-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seeds', models.TextField(help_text='url种子')),
                ('ip', models.TextField(help_text='用户的ip')),
                ('user_id_str', models.TextField(max_length=128)),
                ('user_agent', models.TextField(default='pc', max_length=256)),
                ('encoding', models.CharField(default='utf-8', max_length=16)),
                ('status', models.CharField(default='I', help_text='状态：I:插进来，P：处理中', max_length=1)),
                ('is_grab_out_link', models.BooleanField(default=False)),
                ('result', models.TextField(max_length=128)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spider_task',
            },
        ),
    ]
