# Generated by Django 2.1 on 2019-03-07 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertask',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
