# Generated by Django 2.1 on 2019-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_spidertask_to_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidertask',
            name='result',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
